# Generated by Django 2.0 on 2017-12-24 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_category_create_user', related_query_name='blog_category_create_user', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_category_update_user', related_query_name='blog_category_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category')),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_post_create_user', related_query_name='blog_post_create_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_tag_create_user', related_query_name='blog_tag_create_user', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_tag_update_user', related_query_name='blog_tag_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='update_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_post_update_user', related_query_name='blog_post_update_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
